# Generated by Django 5.1.6 on 2025-02-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenizedstock',
            name='historical_prices',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='stop_loss_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='take_profit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='unrealized_profit_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tokenizedstock',
            name='issuer_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tokenizedstock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tokenizedstock',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
