# Generated by Django 5.1.6 on 2025-02-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_tokenizedstock_historical_prices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenizedstock',
            name='historical_prices',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tokenizedstock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
