# Generated by Django 5.1.6 on 2025-03-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_alter_tokenizedstock_historical_prices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenizedstock',
            name='price_in_xlm',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tokenizedstock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
