# Generated by Django 5.1.6 on 2025-04-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0005_investmentaccount'),
    ]

    operations = [
    ]
