# Generated by Django 5.1.6 on 2025-04-09 10:11

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0006_auto_20250409_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenizedstock',
            options={'ordering': ['symbol']},
        ),
        migrations.AddField(
            model_name='tokenizedstock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tokenizedstock',
            name='price_source',
            field=models.CharField(default='stellarx', max_length=20),
        ),
        migrations.AlterField(
            model_name='tokenizedstock',
            name='historical_prices',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='tokenizedstock',
            name='issuer_address',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='tokenizedstock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tokenizedstock',
            name='price_in_xlm',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddIndex(
            model_name='tokenizedstock',
            index=models.Index(fields=['symbol'], name='invest_toke_symbol_2f7ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenizedstock',
            index=models.Index(fields=['is_active'], name='invest_toke_is_acti_669129_idx'),
        ),
    ]
