# Generated by Django 5.1.6 on 2025-04-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0007_alter_tokenizedstock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenizedstock',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='tokenizedstock',
            name='invest_toke_symbol_2f7ee3_idx',
        ),
        migrations.RemoveIndex(
            model_name='tokenizedstock',
            name='invest_toke_is_acti_669129_idx',
        ),
        migrations.RemoveField(
            model_name='tokenizedstock',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='tokenizedstock',
            name='price_source',
        ),
        migrations.AlterField(
            model_name='tokenizedstock',
            name='historical_prices',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tokenizedstock',
            name='issuer_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tokenizedstock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tokenizedstock',
            name='price_in_xlm',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
