# Generated by Django 5.1.6 on 2025-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0008_alter_tokenizedstock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenizedstock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
