# Generated by Django 5.1.6 on 2025-05-05 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0009_tokenizedstock_last_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userinvestment',
            index=models.Index(fields=['user', 'amount_held'], name='invest_user_user_id_a30972_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvestment',
            index=models.Index(fields=['stop_loss_price'], name='invest_user_stop_lo_e33268_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvestment',
            index=models.Index(fields=['take_profit_price'], name='invest_user_take_pr_b522a8_idx'),
        ),
    ]
