# Generated by Django 5.1.6 on 2025-03-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0002_blogpost_emailcampaign_socialmediapost_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='534063cba5', max_length=10, unique=True),
        ),
    ]
