# Generated by Django 5.1.6 on 2025-03-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0003_blogpost_approved_blogpost_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_automation', models.BooleanField(default=True)),
                ('blog_frequency', models.IntegerField(default=2)),
                ('social_media_frequency', models.IntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='da48c97226', max_length=10, unique=True),
        ),
    ]
