# Generated by Django 5.1.6 on 2025-03-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0004_automationsettings_emailcampaign_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='31e4f26423', max_length=10, unique=True),
        ),
    ]
