# Generated by Django 5.1.6 on 2025-03-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0005_blogpost_slug_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='5b5d874951', max_length=10, unique=True),
        ),
    ]
