# Generated by Django 5.1.6 on 2025-03-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0006_alter_blogpost_slug_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='579ff4a8b2', max_length=10, unique=True),
        ),
    ]
