# Generated by Django 5.1.6 on 2025-03-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0007_alter_blogpost_scheduled_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIContentPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(default='Write an informative blog about {title}')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='cc6919790c', max_length=10, unique=True),
        ),
    ]
