# Generated by Django 5.1.6 on 2025-03-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0008_aicontentprompt_blogpost_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='d1a4b39d99', max_length=10, unique=True),
        ),
    ]
