# Generated by Django 5.1.6 on 2025-03-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0009_alter_referral_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapost',
            name='image',
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='6d25dd24b9', max_length=10, unique=True),
        ),
    ]
