# Generated by Django 5.1.6 on 2025-03-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0010_remove_socialmediapost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='ac17824ba1', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
