# Generated by Django 5.1.6 on 2025-03-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0011_alter_emailcampaign_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='258972da56', max_length=10, unique=True),
        ),
    ]
