# Generated by Django 5.1.6 on 2025-03-07 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0012_socialmediapost_hashtags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='recipients',
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='4c59a372f1', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='recipients',
            field=models.ManyToManyField(related_name='email_campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
