# Generated by Django 5.1.6 on 2025-03-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0013_remove_emailcampaign_recipients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicontentprompt',
            options={'verbose_name': 'AI Content Prompt', 'verbose_name_plural': 'AI Content Prompts'},
        ),
        migrations.AddField(
            model_name='aicontentprompt',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='When this prompt was last modified'),
        ),
        migrations.AddField(
            model_name='aicontentprompt',
            name='prompt_type',
            field=models.CharField(choices=[('blog', 'Blog Post'), ('social_media', 'Social Media Post'), ('email', 'Email Campaign')], default='blog', help_text='The type of content this prompt will generate', max_length=20),
        ),
        migrations.AlterField(
            model_name='aicontentprompt',
            name='prompt',
            field=models.TextField(help_text='Enter the prompt to use for AI content generation'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='6104efd077', max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='aicontentprompt',
            unique_together={('prompt_type',)},
        ),
    ]
