# Generated by Django 5.1.6 on 2025-03-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0014_alter_aicontentprompt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediapost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Social Media Post', 'verbose_name_plural': 'Social Media Posts'},
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='82fa043687', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='content',
            field=models.TextField(help_text='The content of the social media post'),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='hashtags',
            field=models.CharField(blank=True, default=0, help_text='Hashtags for the post', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image URL', null=True),
        ),
    ]
