# Generated by Django 5.1.6 on 2025-03-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0015_alter_socialmediapost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='04c42ba450', max_length=10, unique=True),
        ),
    ]
