# Generated by Django 5.1.6 on 2025-03-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0017_alter_referral_referral_code_dispute_refundlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='e5daaf4d68', max_length=10, unique=True),
        ),
    ]
