# Generated by Django 5.1.6 on 2025-03-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0018_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='9f8f0862aa', max_length=10, unique=True),
        ),
    ]
