# Generated by Django 5.1.6 on 2025-03-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0019_alter_dispute_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='2beb36c139', max_length=10, unique=True),
        ),
    ]
