# Generated by Django 5.1.6 on 2025-03-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0020_alter_dispute_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='287796fde2', max_length=10, unique=True),
        ),
    ]
