# Generated by Django 5.1.6 on 2025-03-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0021_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='e58d1f1e96', max_length=10, unique=True),
        ),
    ]
