# Generated by Django 5.1.6 on 2025-04-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0022_faq_approved_faq_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='recipients',
        ),
        migrations.DeleteModel(
            name='SocialMediaPost',
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='f7b343538e', max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='EmailCampaign',
        ),
    ]
