# Generated by Django 5.1.6 on 2025-04-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0023_remove_emailcampaign_recipients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='02cc8e979d', max_length=10, unique=True),
        ),
    ]
