# Generated by Django 5.1.6 on 2025-04-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0024_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='23af9b4080', max_length=10, unique=True),
        ),
    ]
