# Generated by Django 5.1.6 on 2025-04-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0026_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='e70a16d515', max_length=10, unique=True),
        ),
    ]
