# Generated by Django 5.1.6 on 2025-04-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0027_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='6d96436112', max_length=10, unique=True),
        ),
    ]
