# Generated by Django 5.1.6 on 2025-04-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0028_alter_referral_referral_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
