# Generated by Django 5.1.6 on 2025-04-19 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0029_delete_referral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIContentPrompt',
        ),
        migrations.DeleteModel(
            name='AutomationSettings',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
