# Generated by Django 5.0.3 on 2024-12-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformaccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('vault', 'Vault'), ('utilities_pool', 'Utilities Pool'), ('commission_pool', 'Commission Pool')], max_length=50, null=True),
        ),
    ]
