# Generated by Django 5.1.4 on 2025-02-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('top-up', 'Top-up'), ('data_bundle', 'Data_bundle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operator_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
