# Generated by Django 5.1.4 on 2025-02-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_fee_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('top-up', 'Top-up'), ('data_bundle', 'Data_bundle'), ('utility_payment', 'Utility_payment'), ('gift_card', 'Gift card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('transfer', 'Transfer'), ('airtime', 'Airtime Top-Up'), ('utility', 'Utility Payment'), ('data', 'Data Bundle'), ('gift_card', 'Gift Card Order'), ('shopping', 'Shopping'), ('subscription', 'Subscription'), ('commission', 'Commission')], max_length=20),
        ),
    ]
