# Generated by Django 5.1.4 on 2025-02-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_fee_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
