# Generated by Django 5.1.4 on 2025-02-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userprofile_transaction_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('top-up', 'Top-up'), ('data_bundle', 'Data_bundle'), ('utility_payment', 'Utility_payment'), ('gift_card', 'Gift card'), ('shopping', 'Shopping')], max_length=20),
        ),
    ]
