# Generated by Django 5.1.6 on 2025-03-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_notification_options_notification_read_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReconciliationHistory',
        ),
    ]
