# Generated by Django 5.1.6 on 2025-04-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_reconciliationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3, unique=True)),
                ('rate_to_usd', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='fee',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('top-up', 'Top-up'), ('bundle', 'Bundle'), ('data-bundle', 'Data_bundle'), ('combo-product', 'Combo_product'), ('utility_payment', 'Utility_payment'), ('gift_card', 'Gift card'), ('shopping', 'Shopping')], max_length=20),
        ),
    ]
