# Generated by Django 5.1.6 on 2025-04-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_exchangerate_userprofile_preferred_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='template_used',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
