# Generated by Django 5.1.6 on 2025-04-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_emaillog_error_message_emaillog_template_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='status_code',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
