# Generated by Django 5.1.6 on 2025-04-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_emaillog_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
