# Generated by Django 5.1.6 on 2025-04-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_user_email_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(
                max_length=255, 
                null=True,       # Allows NULL in database
                blank=True,      # Allows empty string in forms/admin
                default=None,    # Explicit default (optional)
            ),
        ),
    ]