# Generated by Django 5.1.6 on 2025-03-16 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_reconciliationhistory'),
        ('drac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancecheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
