# Generated by Django 5.1.6 on 2025-03-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drac', '0002_alter_compliancecheck_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliation',
            name='discrepancy_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
