# Generated by Django 5.1.6 on 2025-03-16 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_reconciliationhistory'),
        ('drac', '0003_reconciliation_discrepancy_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliation',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.transaction'),
        ),
    ]
