# Generated by Django 5.1.11 on 2025-06-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='backup_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
