# Generated by Django 5.1.4 on 2025-02-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
