# Generated by Django 5.1.4 on 2025-02-18 14:02

import storages.backends.dropbox
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_alter_kycrequest_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycrequest',
            name='address_document',
            field=models.FileField(storage=storages.backends.dropbox.DropboxStorage(), upload_to='kyc_documents/address/'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='id_document',
            field=models.FileField(storage=storages.backends.dropbox.DropboxStorage(), upload_to='kyc_documents/id/'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='selfie',
            field=models.FileField(storage=storages.backends.dropbox.DropboxStorage(), upload_to='kyc_documents/selfie/'),
        ),
    ]
