# Generated by Django 5.1.4 on 2025-02-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_alter_kycrequest_address_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycrequest',
            name='address_document',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='id_document',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='selfie',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
