# Generated by Django 5.1.4 on 2025-02-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_alter_kycrequest_address_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycrequest',
            name='address_document',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='id_document',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='selfie',
            field=models.URLField(blank=True, null=True),
        ),
    ]
