# Generated by Django 5.1.4 on 2025-02-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_alter_kycrequest_address_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
